table df_sum_hybrid_fin
	lineageTag: 4bac39c5-5a62-4c89-a662-1a8aae0f88cc

	column doc_id
		dataType: string
		lineageTag: 919b72bc-9c02-406a-a85e-553e8dbbdc28
		summarizeBy: none
		sourceColumn: doc_id

		annotation SummarizationSetBy = Automatic

	column text
		dataType: string
		lineageTag: ae7be3ba-e9a2-49a2-9a90-e9cc30f43cd9
		summarizeBy: none
		sourceColumn: text

		annotation SummarizationSetBy = Automatic

	column summary
		dataType: string
		lineageTag: 96d82a99-a3e2-4c26-a963-4572b0360a34
		summarizeBy: none
		sourceColumn: summary

		annotation SummarizationSetBy = Automatic

	column set
		dataType: string
		lineageTag: b8b5195f-58bf-4e33-a13f-0fbb3ae8e611
		summarizeBy: none
		sourceColumn: set

		annotation SummarizationSetBy = Automatic

	column model
		dataType: string
		lineageTag: 13e488f6-7489-4886-be36-d3689ede007d
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 55ba08c6-bfda-489b-8b9f-191857720120
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column n_doc_sent
		dataType: int64
		formatString: 0
		lineageTag: 846d7895-d7e4-4e70-8d28-007a0a779a11
		summarizeBy: sum
		sourceColumn: n_doc_sent

		annotation SummarizationSetBy = Automatic

	column n_sum_sent
		dataType: int64
		formatString: 0
		lineageTag: 3cde3eeb-88e1-4bc0-860d-cb4fe26e0327
		summarizeBy: sum
		sourceColumn: n_sum_sent

		annotation SummarizationSetBy = Automatic

	column compression
		dataType: double
		lineageTag: 428e1d2b-63fd-479f-8598-45863894a5a0
		summarizeBy: sum
		sourceColumn: compression

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column coverage
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 115fdb2a-aa67-4916-bdcd-ddc2c726a3ac
		summarizeBy: sum
		sourceColumn: coverage

		annotation SummarizationSetBy = Automatic

	column redundancy
		dataType: double
		lineageTag: c32847eb-b8f6-4104-a790-93721da5e2b1
		summarizeBy: sum
		sourceColumn: redundancy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column diversity
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 64e39e0d-6941-4a56-a7b2-fb6a05d17579
		summarizeBy: sum
		sourceColumn: diversity

		annotation SummarizationSetBy = Automatic

	partition df_sum_hybrid_fin = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\KANISORNUN\OneDrive - Allianz\Documents\Mine\IS\Dashboard\df_sum_hybrid_fin.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"doc_id", type text}, {"text", type text}, {"summary", type text}, {"set", type text}, {"model", type text}, {"year", Int64.Type}, {"n_doc_sent", Int64.Type}, {"n_sum_sent", Int64.Type}, {"compression", type number}, {"coverage", type number}, {"redundancy", type number}, {"diversity", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

